### ISSUE TITLE
Smartctl open device: /dev/wd0 failed: Device busy

### ISSUE THREAD

**Issue by bsdhw** [OS108/OS108#3]
Can't get smarts from the internal hard drive:

    sudo smartctl -x /dev/wd0
    Smartctl open device: /dev/wd0 failed: Device busy

Retried many times. Retried after reboot.

dmesg: https://bsd-hardware.info/?probe=f7cb1aa38d&log=dmesg

**Comment by jaypatelani** [comment]
Can you try "sudo atactl wd0 smart status" ?

**Comment by bsdhw** [comment]
> Can you try "sudo atactl wd0 smart status" ?

https://bsd-hardware.info/?probe=0b7b4083bd&log=atactl

```
SMART supported, SMART enabled
id value thresh crit collect reliability description                 raw
  1 100   50     yes online  positive    Raw read error rate         0
  9 100    0     no  online  positive    Power-on hours count        3
 12 100    0     no  online  positive    Device power cycle count    14
168 100    0     no  online  positive    Unknown                     0
170 100   10     yes online  positive    Reserved Block Count        156
173 100    0     no  online  positive    Wear Leveller Worst Case Erase Count 1
192 100    0     no  online  positive    Power-off retract count     1
194  67    0     yes online  positive    Temperature                 33 Lifetime min/max 33/33
218 100   50     yes online  positive    Unknown                     0
231 100    0     yes online  positive    Temperature                 100
241 100    0     no  online  positive    Total LBAs Written          20
```

**Comment by jaypatelani** [comment]
Did you build smartmontools using PkgSrc? smartctl works here.. is your drive wd0?

**Comment by bsdhw** [comment]
It's `smartmontools-7.0nb3` installed by `pkgin install smartmontools`.

The system is installed to `wd0`. No other drives attached except a USB stick.

**Comment by jaypatelani** [comment]
Try smartctl -s on /dev/wd0

Then check with 

smartctl -a /dev/wd0
